// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwhtgerardkbjvjmruvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aHRnZXJhcmRrYmp2am1ydXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzAwNDIsImV4cCI6MjA3MTcwNjA0Mn0.wHJ_Ux7K39hYmNKZx1J6Ei16aHWinFfq1ORMpRr4V-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});